import { TeamMember, Task, Sprint } from "@/types/nexus";

export const initialTeamMembers: TeamMember[] = [
  {
    id: "tm-1",
    name: "Alex Rivera",
    role: "Frontend",
    avatar: "AR",
    currentLoadHours: 36,
    maxCapacityHours: 40,
    avgVelocityPoints: 14,
    skills: ["Next.js", "React 18", "TypeScript", "Tailwind CSS", "Canvas"],
    status: "optimal",
  },
  {
    id: "tm-2",
    name: "Dr. Marcus Chen",
    role: "AI / ML",
    avatar: "MC",
    currentLoadHours: 44,
    maxCapacityHours: 40,
    avgVelocityPoints: 18,
    skills: ["GPT-4 Fine-tuning", "Pinecone Vector DB", "LangChain", "FastAPI"],
    status: "overloaded",
  },
  {
    id: "tm-3",
    name: "Elena Rostova",
    role: "Backend",
    avatar: "ER",
    currentLoadHours: 32,
    maxCapacityHours: 40,
    avgVelocityPoints: 16,
    skills: ["FastAPI", "PostgreSQL", "AsyncIO", "Redis", "Distributed Systems"],
    status: "optimal",
  },
  {
    id: "tm-4",
    name: "Devon Brooks",
    role: "DevOps",
    avatar: "DB",
    currentLoadHours: 24,
    maxCapacityHours: 40,
    avgVelocityPoints: 12,
    skills: ["Kubernetes", "Docker", "AWS ECS", "CI/CD Pipelines", "Terraform"],
    status: "optimal",
  },
  {
    id: "tm-5",
    name: "Sarah Lin",
    role: "Product",
    avatar: "SL",
    currentLoadHours: 38,
    maxCapacityHours: 40,
    avgVelocityPoints: 10,
    skills: ["Sprint Metrics", "User Story Mapping", "Jira Sync", "Release Forecasting"],
    status: "warning",
  },
];

export const initialTasks: Task[] = [
  {
    id: "NX-101",
    title: "Implement Pinecone Vector Index for Semantic Task Search",
    description: "Build 1536-dim embedding index in Pinecone to support sub-100ms semantic similarity search across historical Jira tickets.",
    category: "AI / ML",
    priority: "Critical",
    status: "In Progress",
    assigneeId: "tm-2",
    storyPoints: 8,
    aiPredictedHours: 19.5,
    confidenceScore: 94,
    historicalVariance: "+/- 1.8 hrs",
    riskLevel: "Moderate",
    riskFactors: ["Assignee Dr. Marcus Chen currently over-allocated (44h / 40h)", "Pinecone index cold start latency variance"],
    sprintId: "sp-24",
  },
  {
    id: "NX-102",
    title: "FastAPI Async Predictor Endpoint with Cache Fallback",
    description: "Expose `/predict-velocity` endpoint with Redis caching and Pydantic schema validation for real-time model inference.",
    category: "Backend",
    priority: "High",
    status: "In Progress",
    assigneeId: "tm-3",
    storyPoints: 5,
    aiPredictedHours: 11.2,
    confidenceScore: 91,
    historicalVariance: "+/- 0.9 hrs",
    riskLevel: "Low",
    riskFactors: ["Well-defined schema", "Prior team velocity matches estimate"],
    sprintId: "sp-24",
  },
  {
    id: "NX-103",
    title: "Real-Time Team Workload Heatmap in Next.js 14",
    description: "Interactive visual component with SVG capacity gauges and 1-click AI team workload rebalancing trigger.",
    category: "Frontend",
    priority: "High",
    status: "In Review",
    assigneeId: "tm-1",
    storyPoints: 5,
    aiPredictedHours: 12.8,
    confidenceScore: 96,
    historicalVariance: "+/- 0.6 hrs",
    riskLevel: "Low",
    riskFactors: ["Component isolated", "No external backend blocking dependency"],
    sprintId: "sp-24",
  },
  {
    id: "NX-104",
    title: "Zero-Downtime Blue/Green Deploy on AWS ECS",
    description: "Automate container rollback triggers on latency spikes exceeding 250ms during automated sprint deployments.",
    category: "DevOps",
    priority: "Medium",
    status: "Sprint Ready",
    assigneeId: "tm-4",
    storyPoints: 5,
    aiPredictedHours: 14.0,
    confidenceScore: 88,
    historicalVariance: "+/- 2.1 hrs",
    riskLevel: "Low",
    riskFactors: ["Devon has available bandwidth (24h allocated)"],
    sprintId: "sp-24",
  },
  {
    id: "NX-105",
    title: "GPT-4 Natural Language Query Context Builder with RAG",
    description: "Construct prompt synthesis chain that pulls sprint metadata and task dependencies to answer team inquiries.",
    category: "AI / ML",
    priority: "High",
    status: "Backlog",
    assigneeId: undefined,
    storyPoints: 8,
    aiPredictedHours: 21.0,
    confidenceScore: 89,
    historicalVariance: "+/- 3.2 hrs",
    riskLevel: "High",
    riskFactors: ["Unassigned task", "Token context window budget limits"],
    sprintId: undefined,
  },
  {
    id: "NX-106",
    title: "Telemetry & 40% Beta Delivery Acceleration Analytics",
    description: "Calculates live baseline delivery time vs Nexus AI predictive delivery reduction across active cycles.",
    category: "Product",
    priority: "Medium",
    status: "Sprint Ready",
    assigneeId: "tm-5",
    storyPoints: 3,
    aiPredictedHours: 7.5,
    confidenceScore: 95,
    historicalVariance: "+/- 0.4 hrs",
    riskLevel: "Low",
    riskFactors: ["Clear formula specifications"],
    sprintId: "sp-24",
  },
];

export const initialSprint: Sprint = {
  id: "sp-24",
  name: "Sprint 24: Predictive Velocity Engine",
  goal: "Ship automated task duration prediction, Pinecone vector querying, and real-time workload balancing.",
  capacityPoints: 45,
  allocatedPoints: 38,
  startDate: "Oct 12, 2026",
  endDate: "Oct 26, 2026",
  status: "Active",
};
